#!/usr/bin/env node
"use strict";

// Rebuild the English showcase from reviewed catalogs. No runtime translation,
// network request, external dependency, or private Atlas input is involved.
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const root = path.resolve(__dirname, "..");
const site = path.join(root, "docs/lab-showcase");
const sourceDir = path.join(root, "localization/source");
const catalogDir = path.join(site, "locales/en");
const hash = value => crypto.createHash("sha256").update(value).digest("hex");
const id = value => hash(value).slice(0, 12);
const hasRussian = value => /[А-Яа-яЁё]/.test(value);
const preview = process.argv.includes("--allow-incomplete");
const check = process.argv.includes("--check");
const catalogs = new Map();
const missing = new Map();

function catalog(group) {
  if (!catalogs.has(group)) {
    const file = path.join(catalogDir, `${group}.json`);
    catalogs.set(group, fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf8")) : {});
  }
  return catalogs.get(group);
}
function translate(group, value) {
  const key = id(value), translated = catalog(group)[key];
  if (typeof translated === "string" && translated.length) return translated;
  if (!missing.has(group)) missing.set(group, new Set());
  missing.get(group).add(key);
  return value;
}
function walk(value, group) {
  if (typeof value === "string") return hasRussian(value) ? translate(group, value) : value;
  if (Array.isArray(value)) return value.map(item => walk(item, group));
  if (value && typeof value === "object") return Object.fromEntries(
    Object.entries(value).map(([key, item]) => [key, walk(item, group)]));
  return value;
}
function replaceRanges(source, ranges, lookup) {
  let last = source.length;
  for (const range of [...ranges].sort((a, b) => b.start - a.start)) {
    if (range.end > last || source.slice(range.start, range.end) !== range.source)
      throw new Error(`Invalid or overlapping translation range: ${range.id}`);
    if (range.preserve) { last = range.start; continue; }
    const value = lookup(range.id);
    // Template elements are literal parts only; embedded expressions remain intact.
    const replacement = range.type === "StringLiteral" ? JSON.stringify(value) :
      value.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
    source = source.slice(0, range.start) + replacement + source.slice(range.end);
    last = range.start;
  }
  return source;
}
function build() {
  const outputs = new Map();
  const manifest = JSON.parse(fs.readFileSync(path.join(root, "localization/ranges.json"), "utf8"));
  for (const [file, entry] of Object.entries(manifest)) {
    const source = fs.readFileSync(path.join(site, file), "utf8");
    if (hash(source) !== entry.sha256) throw new Error(`Source changed; refresh translation inventory: ${file}`);
    const strings = new Map(JSON.parse(fs.readFileSync(path.join(sourceDir, `${entry.group}.json`))).entries.map(x => [x.id, x.text]));
    outputs.set(`en/${file}`, replaceRanges(source, entry.ranges, key => translate(entry.group, strings.get(key))));
  }
  for (const [file, globalName, group] of [
    ["research-loop-data", "RESEARCH_LOOP", "research-shared"],
    ["atlas-public", "LAB_ATLAS_DATA", "registry"],
  ]) {
    const source = fs.readFileSync(path.join(site, `data/${file}.js`), "utf8");
    const data = JSON.parse(source.slice(source.indexOf("=") + 1).trim().replace(/;$/, ""));
    let result;
    if (file === "research-loop-data") {
      const { processes, ...shared } = data;
      result = { ...walk(shared, group), processes: processes.map((process, i) => walk(process, i < 4 ? "research-a" : "research-b")) };
      for (const process of result.processes) for (const item of process.gallery || [])
        if (item.src.startsWith("assets/slides/")) item.src = item.src.replace("assets/slides/", "assets/slides/en/");
    } else result = walk(data, group);
    outputs.set(`en/data/${file}.js`, `// Generated by scripts/build_showcase_locales.cjs.\nwindow.${globalName} = ${JSON.stringify(result, null, 2)};\n`);
  }
  const template = fs.readFileSync(path.join(sourceDir, "index.html"), "utf8");
  const shell = JSON.parse(fs.readFileSync(path.join(root, "localization/shell.en.json"), "utf8"));
  let english = template.replace('<html lang="ru">', '<html lang="en">').replace("  <!-- LOCALE_BASE -->\n", "");
  for (const [ru, en] of Object.entries(shell)) {
    if (!english.includes(ru)) throw new Error(`Stale shell translation: ${ru}`);
    english = english.replaceAll(ru, en);
  }
  english = english.replace(/<script src="(?!language\.js)([^"]+)"/g, '<script src="en/$1"');
  outputs.set("index.html", english);
  outputs.set("ru/index.html", template.replace("<!-- LOCALE_BASE -->", '<base href="../">'));
  if (missing.size && !preview) throw new Error(`Incomplete translations: ${[...missing].map(([g, ids]) => `${g}: ${ids.size}`).join(", ")}`);
  for (const [file, content] of outputs) {
    const output = path.join(site, file);
    if (check) {
      if (!fs.existsSync(output) || fs.readFileSync(output, "utf8") !== content)
        throw new Error(`Generated locale is out of date: ${file}`);
    } else {
      fs.mkdirSync(path.dirname(output), { recursive: true });
      fs.writeFileSync(output, content);
    }
  }
  console.log(`${check ? "Checked" : "Built"} ${outputs.size} locale files${missing.size ? " (incomplete preview)" : ""}`);
  if (missing.size) console.log([...missing].map(([g, ids]) => `${g}: ${ids.size} pending`).join("\n"));
}
if (require.main === module) build();
module.exports = { replaceRanges, hash, id };
